### ISSUE TITLE
이미지 저장 서버 띄우기

### ISSUE THREAD

**Issue by simjaeik** [simjaeik/Pets#77]
## :white_check_mark: 작업 내용
- [x] 이미지 저장을 위한 서버 띄우기

**Comment by shshksh** [comment]
새 그룹 생성할 때 group image를 POST body에서 String으로 받던데 이거 Body를 Multipart로 받아서 이미지는 파일로 받아야 할 듯?

**Comment by simjaeik** [comment]
오케오케

**Comment by simjaeik** [comment]
AWS S3 서버 띄우기
